version: "3"
services:
  botservice:
    environment:
      - NATS_URL=nats://nats:4222
    build:
      context: ../
      dockerfile: Docker/Dockerfile.BotService
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - nats
    networks:
      - mynetwork

  redis:
    build:
      context: ../
      dockerfile: Docker/Dockerfile.Redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  nats:
    build:
      context: ../
      dockerfile: Docker/Dockerfile.NATS
    ports:
      - "4222:4222"
    networks:
      - mynetwork

networks:
  mynetwork:
