version: "3"
services:
  botservice:
    environment:
      - NATS_URL=nats://nats:4222
    build:
      context: ../
      dockerfile: Docker/Dockerfile.BotService
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - nats
    networks:
      - mynetwork

  redis:
    build:
      context: ../
      dockerfile: Docker/Dockerfile.Redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  nats:
    build:
      context: ../
      dockerfile: Docker/Dockerfile.NATS
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - mynetwork

  chatroom:
    build:
      context: ../
      dockerfile: Docker/Dockerfile.Chatroom
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - nats
      - botservice
    networks:
      - mynetwork
    environment:
      - REDIS_URL=redis:6379
      - REDIS_USERNAME=thais
      - REDIS_PASSWORD=algodao11
      - NATS_URL=nats://nats:4222
      - JWT_KEY=3Iz842$5nbJ&qSggu4RL

networks:
  mynetwork:
