version: "3"
services:
  botservice:
    environment:
      - NATS_URL=nats://nats:4222
    build:
      context: ../
      dockerfile: Docker/Dockerfile-BotService
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - nats
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - mynetwork

networks:
  mynetwork:
